/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as CorporateEventsRouteImport } from './routes/corporate-events'
import { Route as FacePaintingRouteImport } from './routes/face-painting'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ApiPublicQuoteRequestRouteImport } from './routes/api/public/quote-request'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateEventsRoute = CorporateEventsRouteImport.update({
  id: '/corporate-events',
  path: '/corporate-events',
  getParentRoute: () => rootRouteImport,
} as any)
const FacePaintingRoute = FacePaintingRouteImport.update({
  id: '/face-painting',
  path: '/face-painting',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteRequestRoute = ApiPublicQuoteRequestRouteImport.update({
  id: '/api/public/quote-request',
  path: '/api/public/quote-request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/face-painting': typeof FacePaintingRoute
  '/gallery': typeof GalleryRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/face-painting': typeof FacePaintingRoute
  '/gallery': typeof GalleryRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/face-painting': typeof FacePaintingRoute
  '/gallery': typeof GalleryRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/corporate-events'
    | '/face-painting'
    | '/gallery'
    | '/api/public/quote-request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/corporate-events'
    | '/face-painting'
    | '/gallery'
    | '/api/public/quote-request'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/corporate-events'
    | '/face-painting'
    | '/gallery'
    | '/api/public/quote-request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CorporateEventsRoute: typeof CorporateEventsRoute
  FacePaintingRoute: typeof FacePaintingRoute
  GalleryRoute: typeof GalleryRoute
  ApiPublicQuoteRequestRoute: typeof ApiPublicQuoteRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-events': {
      id: '/corporate-events'
      path: '/corporate-events'
      fullPath: '/corporate-events'
      preLoaderRoute: typeof CorporateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-painting': {
      id: '/face-painting'
      path: '/face-painting'
      fullPath: '/face-painting'
      preLoaderRoute: typeof FacePaintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote-request': {
      id: '/api/public/quote-request'
      path: '/api/public/quote-request'
      fullPath: '/api/public/quote-request'
      preLoaderRoute: typeof ApiPublicQuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CorporateEventsRoute: CorporateEventsRoute,
  FacePaintingRoute: FacePaintingRoute,
  GalleryRoute: GalleryRoute,
  ApiPublicQuoteRequestRoute: ApiPublicQuoteRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
